# Generated by Django 4.2.7 on 2023-11-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techiehub', '0003_feedback_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255)),
                ('field2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
