# Generated by Django 4.2.7 on 2023-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techiehub', '0005_feedback_delete_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Door_Number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
