# Generated by Django 4.2.7 on 2023-12-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techiehub', '0009_student_remove_order_products_delete_customuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
