# Generated by Django 4.2.7 on 2024-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techiehub', '0011_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exp', models.IntegerField()),
                ('skills', models.TextField()),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=15)),
                ('completed_projects', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_dimensions', models.CharField(max_length=255)),
                ('bed_type', models.CharField(max_length=50)),
                ('color_preference', models.CharField(max_length=255)),
                ('budget', models.CharField(max_length=50)),
                ('room_layout', models.TextField()),
                ('comments', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('wardrobe_size', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
